[package]
name = "apple_quality_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
prettytable-rs = "0.10.0"
serde = { version = "1.0.202", features = ["derive", "serde_derive"] }
